Greening-Digital/constellate

- .github/workflows/ci.yml
- cl8-web/.github/workflows/ci.yml
- cl8-web/npm-shrinkwrap.json
- cl8-web/package.json
This PR introduces a github action for installing the constellate javascript code, and running tests when we add new code.
The tests are _supposed_ to fail in this case, as @rmparr is working in another branch to update the dependencies, so we can then got _those_ updated deps to get once again.
> Set up CI for running tests for new code

- cl8-web/package-lock.json
- cl8-web/package.json
This package will allow us to generate code coverage locally and send to coveralls.
> Add coveralls as a dev dependency.

- cl8-web/server/package.json
- cl8-web/server/scripts/clearUsersandDatabase.js
- cl8-web/server/scripts/generateBootstrapUser.js
- cl8-web/server/src/config.js
- cl8-web/src/fbase.js
This PR adds:
- the missing storage library for supporting uploads
- the bootstrap commands for creating users and profiles from a data structure
- a command for resetting the users and profiles stores, so we can easily clear out a constellation
> Add bootstrap and reset scripts, and fix server side auth

- cl8-web/server/npm-shrinkwrap.json
- cl8-web/server/package.json
- cl8-web/server/scripts/generateBootstrapUser.js
This PR adds CSV import/parse functionality to the user bootstrap.
Depending on desired use, the file path can be hard coded, or the main function can accept an argument and pass it to importCsv.
> Add csv import

- cl8-web/tests/unit/specs/store.spec.js
The tests pass locally, but fail on github due to the reliance on a mock server.
> Mark tests as skipped.

- cl8-web/src/components/profile/ProfileSearchItem.vue
This shows photos for users if they have them (albeit at full size), and their names.
If there is no photo, it falls back to gravatar.
> Update sidebar to show user details again

- backend/backend/users/api/serializers.py
- backend/backend/users/models.py
- backend/backend/users/tests/test_models.py
This PR adds the admin status for the JSON representation of profiles in the API.
> Add check for admin for the API

- cl8-web/src/components/profile/ProfileDetail.vue
- cl8-web/src/components/profile/ProfileEdit.vue
- cl8-web/src/components/profile/ProfileSearchItem.vue
- cl8-web/src/main.js
- cl8-web/src/store.js
This PR replaces the Firebase call to fetch profiles with an Axios call to Django.
> Switch out more Firebase bits for Axios calls

- cl8-web/src/components/auth/Login.vue
- cl8-web/src/store.js
This PR utilizes the backend changes made in #36.
The store has a new action to submit an email address, and thus generate an email, plus an updated action for logging in.
The Login Vue component has been updated to conditionally render a `token` field, and dispatch the appropriate actions based on the current login step.
> Implement Passwordless Authentication in Vue

- cl8-web/src/components/profile/ProfileDetail.vue
- cl8-web/src/components/profile/ProfileEdit.vue
- cl8-web/src/components/shared/NavHeaderLoggedIn.vue
- cl8-web/src/store.js
This PR addresses some accessibility, as well as replacing the edit profile firebase bits with axios calls.
> Update edit profile functionality

- cl8-web/src/components/admin/AddUser.vue
- cl8-web/src/store.js
This PR updates the add user functionality to use axios instead of firebase.
It also fixes the isUser property to reference the proper ID field.
> Update add user functionality

- backend/backend/users/api/serializers.py
- backend/backend/users/api/views.py
- backend/backend/users/tests/test_serializer.py
I think I finally got my head around how serialisers are supposed to work in DRF when you are accepting input.
This PR should tidy up the code so it's easier to change and understand, and has some better tests for the expected behavour
> Cleaned up PUT and POST handling on the backend

- cl8-web/src/store.js
This PR changes the updateProfilePhoto action to hit the new API.
API timeout has again been increased to 1 minute to deal with large lists of profiles.
> Change update photo to axios

- cl8-web/src/components/profile/ProfileEdit.vue
- cl8-web/src/components/profile/ProfileTagsComponent.vue
- cl8-web/src/components/shared/NavHeaderEdit.vue
PR includes:
- changes to copy for the form submission buttons
- updates the guidance on naming in the edit view
- removes the use of SCSS in favour of Tachyons classes used elsewhere
> Ca profile copy changes

- backend/backend/users/models.py
This PR includes the ordering of profiles by name, so we being with Abe, and end with Zed.
> Order profiles

- cl8-web/src/components/profile/ProfileEdit.vue
- cl8-web/src/components/profile/ProfileTagsComponent.vue
- cl8-web/src/store.js
- cl8-web/src/utils.js
- cl8-web/tests/unit/specs/ProfileTagsComponent.spec.js
- cl8-web/tests/unit/specs/store.spec.js
This PR:
- removes some overly clever use of javascript Sets in utils
- adds working tests in a few places
- refactors the ProfileTagComponents use more descriptive variable names
> Refactor profile tags

- backend/backend/templates/base.html
- backend/backend/templates/flatpages/default.html
- backend/backend/users/tests/test_serializer.py
- backend/backend/users/tests/test_urls.py
- backend/config/settings/base.py
- backend/config/urls.py
This PR introduces the use of the standard Django flat pages CMS.
Right now we have pages for 'about', and 'privacy'
> CMS flatpages

- .snyk
- Pipfile
- Pipfile.lock
- backend/backend/templates/passwordless_default_token_email.html
- backend/backend/users/tests/test_email.py
- backend/config/settings/base.py
- package-lock.json
- package.json
This PR does two things:
- it updates the copy as defined in [the trello card for work with Icebreaker One](https://trello.com/c/ua5WfZ5F/37-add-new-copy-for-token-email)
- it introduces a the use of [MJML](https://mjml.io/), for rendering responsive html email.
MJML abstracts a lot of the horrorshow of writing HTML email, while still providing a solid foundation for better looking emails.
While you can manually test emails and view them using mailhog, this PR also includes a convenience function designed to allow you to see the rendered email in browser with `view_rendered_html_in_browser`, without needing to go through the login, login email dance every time you want to see how it looks - uncomment line 33 to see it working.
https://github.com/Greening-Digital/constellate/pull/81/files#d …
> Update template email

- cl8-web/src/components/auth/Login.vue
- cl8-web/src/components/profile/ProfileEdit.vue
- cl8-web/tests/unit/specs/__snapshots__/LoginComponent.spec.js.snap
This PR largely introduces copy changes for the new constellation.
> Copy updates for front page, and editing profile link behaviour

- backend/backend/users/api/serializers.py
- backend/backend/users/models.py
- backend/backend/users/tests/factories.py
- backend/backend/users/tests/test_serializer.py
- cl8-web/src/components/profile/ProfileDetail.vue
- cl8-web/src/components/profile/ProfileEdit.vue
- cl8-web/src/components/profile/ProfileSearchItem.vue
This PR adds an organisation field, in the backend, and the front end
> Add organisation field

- backend/backend/templates/invite_new_profile.mjml.html
- backend/backend/templates/invite_new_profile.txt
- backend/backend/users/api/views.py
- backend/backend/users/models.py
- backend/backend/users/tests/test_drf_views.py
- backend/backend/users/tests/test_models.py
- cl8-web/src/components/admin/AddUser.vue
This PR adds invite functionality so when you add a user, you can check a box to send an invite email to them as well. We will need to polish the copy.
> Ca add email invite

- cl8-web/src/components/admin/AddUser.vue
- cl8-web/src/components/auth/Login.vue
- cl8-web/src/components/auth/NewPassword.vue
- cl8-web/src/components/auth/ResetPassword.vue
- cl8-web/src/components/profile/ProfileDetail.vue
- cl8-web/src/components/profile/ProfileEdit.vue
- cl8-web/src/components/profile/ProfilePhoto.vue
- cl8-web/src/components/profile/ProfileTagsComponent.vue
- cl8-web/src/components/shared/NavHeaderEdit.vue
- cl8-web/src/components/shared/NavHeaderLoggedIn.vue
- cl8-web/src/formValidation.js
- cl8-web/src/i18n.js
- cl8-web/src/locales/en.json
- cl8-web/src/main.js
- cl8-web/tests/unit/specs/LoginComponent.spec.js
- cl8-web/tests/unit/specs/ProfileComponent.spec.js
- cl8-web/tests/unit/specs/ProfileDetailComponent.spec.js
- cl8-web/tests/unit/specs/ProfileEditComponent.spec.js
- cl8-web/tests/unit/specs/ProfilePhotoComponent.spec.js
- cl8-web/tests/unit/specs/ProfileTagsComponent.spec.js
- cl8-web/tests/unit/specs/TheProfileList.spec.js
- cl8-web/tests/unit/specs/__snapshots__/LoginComponent.spec.js.snap
- package-lock.json
- package.json
- vue.config.js
This PR moves all of the front end text not coming from the database into internationalization strings.
This has 2 benefits:
- Allow users to edit text on the front end by editing a (relatively) simple JSON file, instead of editing Vue components
- Sets the groundwork for having a multi-language front end in the future
> Add Internationalization to Front End

- Pipfile.lock
- cl8-web/src/components/TheProfileList.vue
- cl8-web/src/components/profile/ProfileDetail.vue
- cl8-web/src/store.js
- cl8-web/tests/unit/specs/ProfileDetailComponent.spec.js
- cl8-web/tests/unit/specs/TheProfileList.spec.js
This PR introduces the ability to filter members by cluster as well as tag in the front end of constellate.
> Add toggling and search for clusters

- backend/backend/conftest.py
- backend/backend/users/admin.py
- backend/backend/users/api/passwordless_urls.py
- backend/backend/users/api/passwordless_views.py
- backend/backend/users/api/views.py
- backend/backend/users/site_admin.py
- backend/backend/users/tests/test_drf_views.py
- backend/config/settings/base.py
- frontend/src/components/TheProfileList.vue
- frontend/src/components/admin/AddUser.vue
- frontend/src/components/profile/ProfileDetail.vue
- frontend/src/components/profile/ProfilePhoto.vue
- frontend/src/locales/en.json
- frontend/src/store.js
- vue.config.js
This PR introduces changes for staff users, allowing for:
- moving profiles to new email addresses if a member switches jobs
- deactivating users for moderating
- controlling tags
> Add administration improvement for staff

- Pipfile
- Pipfile.lock
- cl8/templates/_nav_menu.html
- cl8/templates/_prose_demo.html
- cl8/templates/_sidebar.html
- cl8/templates/pages/home.html
- cl8/users/api/views.py
- cl8/users/filters.py
- config/settings/base.py
- config/settings/local.py
- config/urls.py
- config/wsgi.py
- justfile
- theme/apps.py
- theme/static_src/.gitignore
- theme/static_src/package-lock.json
- theme/static_src/package.json
- theme/static_src/postcss.config.js
- theme/static_src/src/styles.css
- theme/static_src/tailwind.config.js
- theme/templates/base.html
This PR introduces the use of a separate theme app, and a basic listing view, for logged in users.
> Add theme, and listing view

- cl8/templates/_profile.html
- cl8/templates/pages/home.html
- cl8/users/api/views.py
- cl8/users/filters.py
- cl8/users/tests/test_importer_dgen.py
- cl8/users/tests/test_importer_slack.py
This PR:
- Updates our search to use an AND, not an OR when filtering - this lets you start wide, then filter down, toggling as you go
- Adds some light javascript on the front end so on mobile, you toggle between seeing a list of profiles, or a selected profile in most cases
> Ca mobile fix and profile tweak

- Dockerfile
- Pipfile
- Pipfile.lock
- cl8/templates/_nav_menu.html
- cl8/templates/_profile_create.html
- cl8/templates/pages/create_profile.html
- cl8/users/api/views.py
- cl8/users/forms.py
- cl8/users/tests/test_forms.py
- config/urls.py
Add PR adds a new add user page and url, for adding individual users
> Add simple user creation form

- cl8/templates/_profile_edit.html
- cl8/users/forms.py
This adds the missing 'phone' option used in some installations of constellate.
> Add phone as an option for profiles
